apiVersion: v1
kind: Service
metadata:
  annotations:
    enzo: "true"
  labels:
    app: squad2-app
    app.kubernetes.io/instance: squad2-app
    app.kubernetes.io/name: squad2-app
  name: squad2-app-svc
  namespace: squad2-project-space
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: squad2-app
    app.kubernetes.io/name: squad2-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f7580aa1eb6f7176705176e201ecff4de93edafb
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad2_nodeapp_repo
    enzo: "true"
  labels:
    app: squad2-app
    app.kubernetes.io/instance: squad2-app
    app.kubernetes.io/name: squad2-app
    app.openshift.io/runtime: js
  name: squad2-app-deployment
  namespace: squad2-project-space
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: squad2-app
      app.kubernetes.io/name: squad2-app
  template:
    metadata:
      annotations:
        enzo: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: squad2-app
        app.kubernetes.io/name: squad2-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/kuldeeps_ibm/squad2-app:39a0b29b866f05840037bc7acb277b6711d55633
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: squad2-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    enzo: "true"
    openshift.io/host.generated: "true"
  name: kspfs
  namespace: squad2-project-space
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: squad2-app-svc
    weight: 100
  wildcardPolicy: None
